# Build settings
title: Minimalist theme
  #logo: /assets/img/logo.png
color-scheme: auto
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
theme: Bay
